<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casas_rurales [
  <!ELEMENT casas_rurales (casa+)>
  <!ELEMENT casa (direccion, descripcion+, estado, (tamanio | hectareas),disponible?)>
  <!ELEMENT direccion (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT estado (#PCDATA)>
  <!ELEMENT tamanio (#PCDATA)>
  <!ELEMENT hectareas (#PCDATA)>
  <!ELEMENT disponible EMPTY>
]>
<casas_rurales>
  <casa>
    <direccion>Avenida de los rosales</direccion>
    <descripcion>Casa rural de verano con piscina</descripcion>
    <estado>Disponible</estado>
    <tamanio>200m2</tamanio>
    <disponible/>
  </casa>
  <casa>
    <direccion>Avenida de los pinos</direccion>
    <descripcion>Casa rural en la monta√±a</descripcion>
    <estado>Disponible</estado>
    <hectareas>1h</hectareas>
    <disponible/>
  </casa>
</casas_rurales>