=== CristianPG1993/Lenguaje-de-marcas/clase2209/empresa.dtd
<!ELEMENT empresa (empleado+)>
<!ELEMENT empleado (nombre, puesto, salario)>
<!ATTLIST empleado id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT puesto (#PCDATA)>
<!ATTLIST puesto nombre (DEV | SY | DES) #REQUIRED>
<!ELEMENT salario (#PCDATA)>
<!ATTLIST salario moneda (USD | EUR | JPY) #REQUIRED>

=== CristianPG1993/Lenguaje-de-marcas/clase2209/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">

<empresa>
    <empleado id="e1">
        <nombre>Juan Pérez</nombre>
        <puesto nombre="DEV"/>
        <salario moneda="EUR">50000</salario>
    </empleado>
    <empleado id="e2">
        <nombre>María López</nombre>
        <puesto nombre="DES"/>
        <salario moneda="USD">45000</salario>
    </empleado>
</empresa>
